export {
  NODE_TOOLS_VERSION,
  ROOT_DERIVATION_DOMAIN_LABEL,
  NODE_TOOLS_SCRYPT,
  type NodeCredentialMaterial,
  deriveRootKeyFromSecret,
  deriveNodeIdFromMaterial,
  hashNodePassword,
  normalizeNodePassphrase,
  nodeCredentialsMaterialFromHumanPassphrase,
  generateNodePassw,
  nodeCredentialFromHumanPhrase,
  nodeCredentialFromPasswHash,
  createNodeCredentialMaterial,
  verifyStoredNodeCredential,
} from "./derivation.js";
