export type { AgentPlaySnapshot, AgentPlayWorldLayout } from "./public-types.js";
export type { WorldBounds } from "./lib/world-bounds.js";
export {
  clampWorldPosition,
  boundsContain,
  expandBoundsToMinimumPlayArea,
  MINIMUM_PLAY_WORLD_BOUNDS,
  MINIMUM_STREET_LAYOUT_BOUNDS,
  DEFAULT_LAYOUT_BOUNDS_WITH_PARKING,
} from "./lib/world-bounds.js";
export {
  type OccupancyGridPoint,
  CONTINUOUS_RENDER_OFFSET,
  OCCUPANCY_POINT_MULTIPLIER,
  DEFAULT_AGENT_SPAWN_MIN_DISTANCE,
  SPACE_STRUCTURE_ANCHOR_MIN_DISTANCE,
  SPATIAL_ZONE_INDEX_AGENTS,
  SPATIAL_ZONE_INDEX_SPACES,
  spatialZoneBounds,
  spatialZoneCenter,
  pointCellInSpatialZone,
  pointCellInRect,
  listOccupancyPointsInRect,
  listOccupancyPointsForSpatialZone,
  listAllowedOccupancyPoints,
  occupancyPointsGroupedBySpatialZone,
  occupancyKeyForPosition,
  buildRankedOccupancyPointsInRect,
  buildRankedOccupancyPointsForSpatialZone,
  buildRankedOccupancyPoints,
  boundingWorldRectForOccupancyPoints,
  isAgentSpawnOccupancyPointAvailableInRect,
  isSpaceAnchorOccupancyPointAvailableInRect,
  isAgentSpawnOccupancyPointAvailable,
  isSpaceAnchorOccupancyPointAvailable,
} from "./lib/occupancy-grid-model.js";
export {
  STREET_NAME_POOL,
  type StreetPoolEntry,
  getStreetPoolEntryById,
} from "./lib/world-streets-pool.js";
export {
  type OccupantGroup,
  type Street,
  type Zone,
  type WorldLayout,
  streetFromPoolEntry,
  zonesForGroup,
  primaryZoneForGroup,
  enumerateIntegerCellsInRect,
  cellsForZone,
  centerOfZone,
  pointCellInZone,
  listOccupancyPointsForZone,
  buildRankedOccupancyPointsForZone,
  occupancyPointsGroupedByZones,
  nextStreetFromPool,
  pickZoneForGroup,
  availableCellsForZone,
  isAgentSpawnOccupancyPointAvailableInZone,
  isSpaceAnchorOccupancyPointAvailableInZone,
  createVerticalStripSeedLayout,
  createWorldLayoutWithParkingRow,
  migrateLayoutToParkingRow,
  layoutHasParkingZone,
  migrateWorldLayoutBounds,
  applyBoundsFieldUpdateToLayout,
  type WorldLayoutBoundsField,
} from "./lib/world-layout-model.js";
export {
  CarWashCarSchema,
  DEFAULT_PLAYER_WALLET_BALANCE_USD,
  PlayerWalletSchema,
  PurchaseRecordSchema,
  SaleStateSchema,
  ShopItemSchema,
  SupermarketItemSchema,
  createInitialPlayerWallet,
  createInitialAgentRewardWallet,
  desaturateColor,
  isItemAvailableForPurchase,
  type CarWashCar,
  type PlayerWallet,
  type PurchaseRecord,
  type SaleState,
  type ShopItem,
  type SpaceContentItem,
  type SupermarketItem,
} from "./lib/space-content-model.js";
export {
  ParkingDurationTierSchema,
  ParkingSpotSchema,
  ParkingStreetContentSchema,
  createEmptyParkingStreetContent,
  findParkingSpot,
  listActiveParkingOccupancies,
  PARKING_BAY_COUNT,
  PARKING_LAYERS_PER_BAY,
  PARKING_SPOT_COUNT,
  type ParkingSpot,
  type ParkingOccupant,
  type ParkingStreetContent,
} from "./lib/parking-content-model.js";
export {
  DEFAULT_PARKING_RATES_USD,
  PARKING_DURATION_TIERS,
  computeParkingExpiresAt,
  effectiveHourlyRateUsd,
  isParkingOccupantActive,
} from "./lib/parking-pricing.js";
export {
  canNodeAcquireParkingSpot,
  MAX_SLOTS_WITH_FOREVER,
  MAX_TIMED_PARKING_SLOTS_PER_NODE,
  type ParkingDurationTier,
  type ParkingOccupancyRef,
  type ParkingOwnershipError,
} from "./lib/parking-ownership.js";
export {
  APU_TOKEN,
  buildAmenityPurchaseApuFields,
  buildApuWalletTransaction,
  buildWalletBundleApuFields,
} from "./lib/wallet-apu-transaction.js";
export {
  TALK_PRICE_PER_60S_USD,
  TALK_PRICE_PER_SECOND_USD,
  TALK_TICK_SECONDS,
  costForSeconds,
} from "./lib/talk-billing.js";
export {
  TALK_AGENT_PU_BILLED_SECONDS_PER_UNIT,
  TALK_AGENT_PU_MAX_PER_LEG,
  computeTalkAgentPowerUpsEarned,
  type ComputeTalkAgentPowerUpsEarnedInput,
} from "./lib/talk-agent-reward.js";
export {
  WALLET_BUNDLE_OFFERS,
  getWalletBundleById,
  type WalletBundleId,
  type WalletBundleOffer,
} from "./lib/wallet-bundle-catalog.js";
export {
  GAME_CABINET_CATALOG,
  PLAYABLE_GAME_IDS,
  featuredGameIdForUtcDate,
  getGameCabinetByGameId,
  getGameCabinetById,
  isGameId,
  type GameCabinetEntry,
  type GameId,
} from "./lib/game-catalog.js";
export {
  ApplyGameOutcomeInputSchema,
  DAILY_GAME_PU_CAP,
  GameEventSchema,
  GamePerTitleStatsSchema,
  GameStatsSchema,
  computeRoundPuDelta,
  createEmptyGameStats,
  utcDateKey,
  type ApplyGameOutcomeInput,
  type GameEvent,
  type GamePerTitleStats,
  type GameStats,
} from "./lib/game-outcome-model.js";
export {
  ScannerBlockRecordSchema,
  ScannerHeadSchema,
  ScannerMigrationStateSchema,
  ScannerNodeProfileSchema,
  ScannerTxRecordSchema,
  ScannerWalletSnapshotSchema,
  type ScannerBlockRecord,
  type ScannerHead,
  type ScannerMigrationState,
  type ScannerNodeProfile,
  type ScannerTxRecord,
  type ScannerWalletSnapshot,
} from "./lib/scanner-model.js";
export {
  ANALYTICS_EVENT_NAMES,
  AnalyticsEventSchema,
  AnalyticsTraitsSchema,
  type AnalyticsEvent,
  type AnalyticsEventName,
  type AnalyticsTraits,
} from "./lib/analytics-event-model.js";
export {
  mergeSnapshotWithPlayerChainNode,
  parsePlayerChainFanoutNotify,
  parsePlayerChainFanoutNotifyFromSsePayload,
  parsePlayerChainNodeRpcBody,
  sortNodeRefsForSerializedFetch,
} from "./lib/player-chain-merge.js";
export {
  PLAYER_CHAIN_GENESIS_STABLE_KEY,
  PLAYER_CHAIN_HEADER_STABLE_KEY,
} from "./lib/world-chain-keys.js";
